# Generated by Django 6.0.7 on 2026-08-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_bus_driver_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='shape_geometry',
            field=models.JSONField(blank=True, default=list, help_text='Road-aligned polyline waypoints [[lat, lng], ...]'),
        ),
    ]
