# Generated by Django 6.0.7 on 2026-09-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_route_shape_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='trip_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_TRANSIT', 'In Transit'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20),
        ),
    ]
