# Generated by Django 6.0.2 on 2026-09-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_bus_trip_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='trip_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('ACTIVE', 'Active'), ('IN_PROGRESS', 'In Progress'), ('IN_TRANSIT', 'In Transit'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NOT_STARTED', max_length=20),
        ),
    ]
